{
 "title": "Example",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } }
  ]
 },
 "panels": [
  {
   "title": "Requisições recebidas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri, status) (rate(http_server_requests_seconds_count{application=\"$application\", uri!=\"/actuator/prometheus\", uri!=\"/**\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Tempo e status das requisições recebidas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(uri, status, method) ((rate(http_server_requests_seconds_sum{application=\"$application\", uri!=\"/actuator/prometheus\"}[$__rate_interval]) * 1000) / (rate(http_server_requests_seconds_count{application=\"$application\"}[$__rate_interval]) > 0))",
     "legendFormat": "[{{status}}] {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requisições realizadas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri) (rate(http_client_requests_seconds_count{application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Tempo e status das requisições realizadas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(http_client_requests_seconds_sum{application=\"$application\"}[$__rate_interval]) * 1000) / (rate(http_client_requests_seconds_count{application=\"$application\"}[$__rate_interval]) > 0)",
     "legendFormat": "[{{status}}] {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requisições em execução",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "http_client_requests_active_seconds_active_count{application=\"$application\"}",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  }
 ]
}