server:
  port: 8003
  servlet:
    context-path: /service-c
spring:
  application:
    name: @artifactId@
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus
  server:
    port: 9003